base_model_name: "./checkpoints/sft"  # The SFT model
model_checkpoint: ""                  # If resuming a partially-trained reward model
save_dir: "./checkpoints/reward"
data_path: "./data/reward/sample_reward.jsonl"
train_batch_size: 2
max_steps: 200
learning_rate: 1e-5
warmup_steps: 10
max_length: 256
mixed_precision: "fp16"
logging_steps: 10
